all:
	@$(MAKE) -C fig-exact all;
	@$(MAKE) -C convergence all;
	@$(MAKE) -C application all;
	@$(MAKE) -C anode-numerotations all;

clean:
	@$(MAKE) -C fig-exact clean;
	@$(MAKE) -C convergence clean;
	@$(MAKE) -C application clean;
	@$(MAKE) -C anode-numerotations clean;
