all:
	@cd solidfraction; $(MAKE) all
	@cd enthalpy; $(MAKE) all
	@cd beta; $(MAKE) all
	@cd temperature; $(MAKE) all
	@cd remelt; $(MAKE) all
	@cd diss-rate; $(MAKE) all
	@cd dissolution; $(MAKE) all
	@cd fall; $(MAKE) all
	@cd trajectories; $(MAKE) all
	@cd characteristics; $(MAKE) all

clean:
	@cd solidfraction; $(MAKE) clean
	@cd enthalpy; $(MAKE) clean
	@cd beta; $(MAKE) clean
	@cd temperature; $(MAKE) clean
	@cd remelt; $(MAKE) clean
	@cd diss-rate; $(MAKE) clean
	@cd dissolution; $(MAKE) clean
	@cd fall; $(MAKE) clean
	@cd trajectories; $(MAKE) clean
	@cd characteristics; $(MAKE) clean
