all:
	@cd solidfraction; $(MAKE) all
	@cd enthalpy; $(MAKE) all
	@cd beta; $(MAKE) all
	@cd temperature; $(MAKE) all

clean:
	@cd solidfraction; $(MAKE) clean
	@cd enthalpy; $(MAKE) clean
	@cd beta; $(MAKE) clean
	@cd temperature; $(MAKE) clean
