all:
	@$(MAKE) -C introduction/ all
	@$(MAKE) -C particles/ all
	@$(MAKE) -C populations/ all
	@$(MAKE) -C fourier/ all


clean:
	@$(MAKE) -C introduction/ clean
	@$(MAKE) -C particles/ clean
	@$(MAKE) -C populations/ clean
	@$(MAKE) -C fourier/ clean
