all:
	@$(MAKE) -C ap32-mesh-components all;
	@$(MAKE) -C ap32-fluid-flow all;
	@$(MAKE) -C cadence all;
	@$(MAKE) -C anode-configuration all;
	@$(MAKE) -C variances all;

clean:
	@$(MAKE) -C ap32-mesh-components clean;
	@$(MAKE) -C ap32-fluid-flow clean;
	@$(MAKE) -C cadence clean;
	@$(MAKE) -C anode-configuration clean;
	@$(MAKE) -C variances clean;
